import type { ChannelFormatter } from "@/lib/formatters/types";
import type { ReportOutput } from "@/lib/types/brief";

export class EmailFormatter implements ChannelFormatter {
  async format(data: ReportOutput): Promise<string> {
    const { summary, actions, subjectLine } = data;

    return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${subjectLine}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;1,9..144,400&family=Jost:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
  :root{
    --ink:#1c1916;--ink-soft:#5a534b;--ivory:#f7f2e9;--paper:#fffdf8;
    --line:#e3dac9;--gold:#a9772f;--oxblood:#6e2b2b;--sage:#7d8466;
  }
  *{box-sizing:border-box;margin:0;padding:0;}
  html{-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  body{
    font-family:'Jost',-apple-system,sans-serif;background:var(--ivory);color:var(--ink);
    line-height:1.5;padding:48px 24px;
    background-image:radial-gradient(circle at 18% 12%, rgba(201,163,94,.07), transparent 38%),
                     radial-gradient(circle at 90% 80%, rgba(110,43,43,.05), transparent 40%);
  }
  .sheet{max-width:860px;margin:0 auto;background:var(--paper);border:1px solid var(--line);
    box-shadow:0 30px 60px -30px rgba(28,25,22,.28);position:relative;overflow:hidden;}
  .sheet::before{content:"";position:absolute;top:0;left:0;right:0;height:5px;
    background:linear-gradient(90deg,var(--oxblood),var(--gold));}

  .masthead{padding:46px 52px 30px;border-bottom:1px solid var(--line);}
  .kicker{font-size:11px;letter-spacing:.42em;text-transform:uppercase;color:var(--gold);font-weight:500;margin-bottom:16px;}
  .title{font-family:'Fraunces',serif;font-weight:400;font-size:42px;line-height:1.1;letter-spacing:-.01em;margin-bottom:12px;}
  .title em{font-style:italic;color:var(--oxblood);}
  .subtitle{font-size:14.5px;color:var(--ink-soft);max-width:60ch;line-height:1.55;}

  section{padding:34px 52px;border-bottom:1px solid var(--line);}
  .sec-label{font-family:'Fraunces',serif;font-size:13px;letter-spacing:.32em;text-transform:uppercase;
    color:var(--gold);margin-bottom:18px;font-weight:500;}

  .summary-block{background:rgba(201,163,94,.04);padding:28px;border-left:4px solid var(--gold);margin-bottom:28px;font-size:15px;line-height:1.6;}
  .summary-block strong{color:var(--oxblood);font-weight:500;}

  .adv-item{display:flex;gap:18px;padding:16px 0;border-bottom:1px solid var(--line);}
  .adv-item:last-child{border-bottom:none;padding-bottom:0;}
  .adv-num{font-family:'Fraunces',serif;font-style:italic;font-size:26px;color:var(--gold);line-height:1;flex:none;width:34px;margin-top:2px;}
  .adv-body h4{font-size:15px;font-weight:500;margin-bottom:6px;color:var(--ink);}
  .adv-body p{font-size:13.5px;color:var(--ink-soft);line-height:1.55;}

  footer{padding:22px 52px 30px;font-size:11px;color:var(--ink-soft);line-height:1.55;border-top:1px solid var(--line);}

  @media print{body{padding:0;background:#fff;}.sheet{box-shadow:none;border:none;max-width:100%;}}
  @media(max-width:720px){
    .masthead{padding:30px 24px;}
    .title{font-size:32px;}
    section{padding:24px;}
    .sheet::before{height:3px;}
  }
</style>
</head>
<body>
<div class="sheet">

  <div class="masthead">
    <div class="kicker">Monthly Analytics Brief</div>
    <h1 class="title">${subjectLine}</h1>
    <p class="subtitle">Performance insights and recommendations for the month ahead.</p>
  </div>

  <section>
    <div class="sec-label">Summary</div>
    <div class="summary-block">
      ${summary}
    </div>
  </section>

  <section class="advice">
    <div class="sec-label">Recommended Actions</div>
    ${actions ? actions.map((action, i) => `<div class="adv-item"><div class="adv-num">${i + 1}</div><div class="adv-body"><p>${action}</p></div></div>`).join("") : ""}
  </section>

  <footer>
    <div>This report was generated by AI analysis of your website analytics. For detailed metrics and trends, visit your analytics dashboard.</div>
  </footer>

</div>
</body>
</html>
    `;
  }
}
